# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Aplikacja_geodezyjna.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Aplikacja_geodezyjna(object):
    def setupUi(self, Aplikacja_geodezyjna):
        Aplikacja_geodezyjna.setObjectName("Aplikacja_geodezyjna")
        Aplikacja_geodezyjna.resize(580, 455)
        self.Wprowadz_phi = QtWidgets.QLabel(Aplikacja_geodezyjna)
        self.Wprowadz_phi.setGeometry(QtCore.QRect(30, 170, 271, 31))
        self.Wprowadz_phi.setTextFormat(QtCore.Qt.RichText)
        self.Wprowadz_phi.setObjectName("Wprowadz_phi")
        self.Wprowadz_lambde = QtWidgets.QLabel(Aplikacja_geodezyjna)
        self.Wprowadz_lambde.setGeometry(QtCore.QRect(30, 210, 271, 31))
        self.Wprowadz_lambde.setTextFormat(QtCore.Qt.RichText)
        self.Wprowadz_lambde.setObjectName("Wprowadz_lambde")
        self.Wyswietlenie_wyniku_xy00 = QtWidgets.QLabel(Aplikacja_geodezyjna)
        self.Wyswietlenie_wyniku_xy00.setGeometry(QtCore.QRect(260, 300, 281, 31))
        self.Wyswietlenie_wyniku_xy00.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Wyswietlenie_wyniku_xy00.setText("")
        self.Wyswietlenie_wyniku_xy00.setObjectName("Wyswietlenie_wyniku_xy00")
        self.Wartosc_phi = QtWidgets.QLineEdit(Aplikacja_geodezyjna)
        self.Wartosc_phi.setGeometry(QtCore.QRect(320, 170, 111, 31))
        self.Wartosc_phi.setObjectName("Wartosc_phi")
        self.Wartosc_lambdy = QtWidgets.QLineEdit(Aplikacja_geodezyjna)
        self.Wartosc_lambdy.setGeometry(QtCore.QRect(320, 210, 111, 31))
        self.Wartosc_lambdy.setObjectName("Wartosc_lambdy")
        self.groupBox_strefy = QtWidgets.QGroupBox(Aplikacja_geodezyjna)
        self.groupBox_strefy.setGeometry(QtCore.QRect(260, 30, 171, 121))
        self.groupBox_strefy.setTitle("")
        self.groupBox_strefy.setObjectName("groupBox_strefy")
        self.Strefa_5 = QtWidgets.QRadioButton(self.groupBox_strefy)
        self.Strefa_5.setGeometry(QtCore.QRect(10, 30, 111, 17))
        self.Strefa_5.setObjectName("Strefa_5")
        self.Strefa_u2000 = QtWidgets.QLabel(self.groupBox_strefy)
        self.Strefa_u2000.setGeometry(QtCore.QRect(10, 10, 161, 16))
        self.Strefa_u2000.setTextFormat(QtCore.Qt.RichText)
        self.Strefa_u2000.setObjectName("Strefa_u2000")
        self.Strefa_6 = QtWidgets.QRadioButton(self.groupBox_strefy)
        self.Strefa_6.setGeometry(QtCore.QRect(10, 50, 131, 17))
        self.Strefa_6.setObjectName("Strefa_6")
        self.Strefa_7 = QtWidgets.QRadioButton(self.groupBox_strefy)
        self.Strefa_7.setGeometry(QtCore.QRect(10, 70, 141, 17))
        self.Strefa_7.setObjectName("Strefa_7")
        self.Strefa_8 = QtWidgets.QRadioButton(self.groupBox_strefy)
        self.Strefa_8.setGeometry(QtCore.QRect(10, 90, 141, 17))
        self.Strefa_8.setObjectName("Strefa_8")
        self.groupBox_elipsoida = QtWidgets.QGroupBox(Aplikacja_geodezyjna)
        self.groupBox_elipsoida.setGeometry(QtCore.QRect(30, 30, 191, 101))
        self.groupBox_elipsoida.setTitle("")
        self.groupBox_elipsoida.setObjectName("groupBox_elipsoida")
        self.Elipsoida = QtWidgets.QLabel(self.groupBox_elipsoida)
        self.Elipsoida.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.Elipsoida.setTextFormat(QtCore.Qt.RichText)
        self.Elipsoida.setObjectName("Elipsoida")
        self.GRS80 = QtWidgets.QRadioButton(self.groupBox_elipsoida)
        self.GRS80.setGeometry(QtCore.QRect(10, 30, 86, 17))
        self.GRS80.setObjectName("GRS80")
        self.WGS84 = QtWidgets.QRadioButton(self.groupBox_elipsoida)
        self.WGS84.setGeometry(QtCore.QRect(10, 60, 86, 17))
        self.WGS84.setObjectName("WGS84")
        self.xy2000 = QtWidgets.QPushButton(Aplikacja_geodezyjna)
        self.xy2000.setGeometry(QtCore.QRect(30, 300, 121, 31))
        self.xy2000.setObjectName("xy2000")
        self.xy_gk = QtWidgets.QPushButton(Aplikacja_geodezyjna)
        self.xy_gk.setGeometry(QtCore.QRect(30, 380, 121, 31))
        self.xy_gk.setObjectName("xy_gk")
        self.Wyswietlenie_wyniku_xy_gk = QtWidgets.QLabel(Aplikacja_geodezyjna)
        self.Wyswietlenie_wyniku_xy_gk.setGeometry(QtCore.QRect(260, 380, 281, 31))
        self.Wyswietlenie_wyniku_xy_gk.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Wyswietlenie_wyniku_xy_gk.setText("")
        self.Wyswietlenie_wyniku_xy_gk.setObjectName("Wyswietlenie_wyniku_xy_gk")
        self.Wybor = QtWidgets.QLabel(Aplikacja_geodezyjna)
        self.Wybor.setGeometry(QtCore.QRect(30, 270, 181, 21))
        self.Wybor.setTextFormat(QtCore.Qt.RichText)
        self.Wybor.setObjectName("Wybor")
        self.Wyswietlenie_wyniku_xy92 = QtWidgets.QLabel(Aplikacja_geodezyjna)
        self.Wyswietlenie_wyniku_xy92.setGeometry(QtCore.QRect(260, 340, 281, 31))
        self.Wyswietlenie_wyniku_xy92.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Wyswietlenie_wyniku_xy92.setText("")
        self.Wyswietlenie_wyniku_xy92.setObjectName("Wyswietlenie_wyniku_xy92")
        self.xy92 = QtWidgets.QPushButton(Aplikacja_geodezyjna)
        self.xy92.setGeometry(QtCore.QRect(30, 340, 121, 31))
        self.xy92.setObjectName("xy92")
        self.model1 = QtWidgets.QLabel(Aplikacja_geodezyjna)
        self.model1.setGeometry(QtCore.QRect(160, 380, 91, 31))
        self.model1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.model1.setText("")
        self.model1.setObjectName("model1")
        self.model2 = QtWidgets.QLabel(Aplikacja_geodezyjna)
        self.model2.setGeometry(QtCore.QRect(160, 340, 91, 31))
        self.model2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.model2.setText("")
        self.model2.setObjectName("model2")
        self.model3 = QtWidgets.QLabel(Aplikacja_geodezyjna)
        self.model3.setGeometry(QtCore.QRect(160, 300, 91, 31))
        self.model3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.model3.setText("")
        self.model3.setObjectName("model3")

        self.retranslateUi(Aplikacja_geodezyjna)
        QtCore.QMetaObject.connectSlotsByName(Aplikacja_geodezyjna)

    def retranslateUi(self, Aplikacja_geodezyjna):
        _translate = QtCore.QCoreApplication.translate
        Aplikacja_geodezyjna.setWindowTitle(_translate("Aplikacja_geodezyjna", "Dialog"))
        self.Wprowadz_phi.setText(_translate("Aplikacja_geodezyjna", "Podaj wartość phi w stopniach dziesiętnych"))
        self.Wprowadz_lambde.setText(_translate("Aplikacja_geodezyjna", "Podaj wartość lambdy w stopniach dziesiętnych"))
        self.Strefa_5.setText(_translate("Aplikacja_geodezyjna", "5 --> 15 stopni"))
        self.Strefa_u2000.setText(_translate("Aplikacja_geodezyjna", "Wybierz strefę dla u2000"))
        self.Strefa_6.setText(_translate("Aplikacja_geodezyjna", "6 --> 18 stopni"))
        self.Strefa_7.setText(_translate("Aplikacja_geodezyjna", "7 --> 21 stopni"))
        self.Strefa_8.setText(_translate("Aplikacja_geodezyjna", "8 --> 24 stopnie"))
        self.Elipsoida.setText(_translate("Aplikacja_geodezyjna", "Wybierz elipsoidę odniesienia"))
        self.GRS80.setText(_translate("Aplikacja_geodezyjna", "GRS80"))
        self.WGS84.setText(_translate("Aplikacja_geodezyjna", "WGS84"))
        self.xy2000.setText(_translate("Aplikacja_geodezyjna", "Przelicz na xy2000"))
        self.xy_gk.setText(_translate("Aplikacja_geodezyjna", "Przelicz na xy_gk00"))
        self.Wybor.setText(_translate("Aplikacja_geodezyjna", "Wybierz, co chcesz zrobić"))
        self.xy92.setText(_translate("Aplikacja_geodezyjna", "Przelicz na xy1992"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Aplikacja_geodezyjna = QtWidgets.QDialog()
    ui = Ui_Aplikacja_geodezyjna()
    ui.setupUi(Aplikacja_geodezyjna)
    Aplikacja_geodezyjna.show()
    sys.exit(app.exec_())

